### ISSUE TITLE
Load the URIs dynamically from a .yaml 

### ISSUE THREAD

**Issue by edgars** [qriar-labs/multi-apigateway-proxy#1]
Load the URI from external .yaml

```
spring:
  cloud:
    gateway:
      routes:
      - id: get
        uri: http://httpbin.org
        predicates:
        - Path=/**
```
